defaults:
  - /mcpp.config
  - _self_


paths:
  repo_root: ${oc.env:REPO_ROOT}
  data_root: ${paths.repo_root}/data
  out_root: ${paths.repo_root}/out-data
  lib_root: ${paths.repo_root}/lib
  log_root: ${paths.out_root}/logs
  reports: ${paths.out_root}/reports


base:
  jobs: 16


treesitter:
  build_path: ${paths.repo_root}/build/tree-sitter.so
  libraries:
    - ${paths.lib_root}/tree-sitter-c
    - ${paths.lib_root}/tree-sitter-cpp


hydra:
  run:
    dir: ${paths.log_root}/mcpp-${now:%Y-%m-%d-%H-%M-%S}
