defaults:
  - /mcpp.config
  - _self_


in_path: ${paths.data_root}
out_path: ${paths.out_root}/mcpp.json
metrics:
 - C1
 - C2
 - C3
 - C4
 - V1
 - V2
 - V3
 - V4
 - V5
 - V6
 - V7
 - V8
 - V9
 - V10
 - V11
 - x1
 - x2
 - x3
 - x4
 - t1
 - t2
 - t3
 - s1
 - s2
 - s3
 - s4
 - m1
 - m2


paths:
  repo_root: ${oc.env:REPO_ROOT}
  lib_root: ${paths.repo_root}/lib
  data_root: ./data
  out_root: ./out-data
  log_root: ${paths.out_root}/logs


hydra:
  run:
    dir: ${paths.log_root}/mcpp-${now:%Y-%m-%d-%H-%M-%S}
